apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-ssoserver-sample
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        name: ssoserver-deployment
    spec:
      containers:
      - name: microservice-ssoserver
        image: microservice-ssoserver:latest        
        ports:
          - containerPort: 9443
        imagePullPolicy: IfNotPresent
        env:
          - name: MB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-keystore-password
                key: password
          - name: MB_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-truststore-password
                key: password
          - name: EXTERNAL_IP_ADDR
            valueFrom:
              configMapKeyRef:
                name: ipaddr-config
                key: EXTERNAL_IP_ADDR                
        volumeMounts:
        - name: keystore
          mountPath: /etc/wlp/config/keystore
        - name: truststore
          mountPath: /etc/wlp/config/truststore
        - name: liberty-config
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configMount
        - name: userids
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/useridMount
      volumes:
      - name: keystore
        secret:
          secretName: mb-keystore
      - name: truststore
        secret:
          secretName: mb-truststore
      - name: userids
        secret:
          secretName: liberty-userids
      - name: liberty-config
        configMap:
          name: liberty-config
          items:
            - key: keystore.xml
              path: keystore.xml
            - key: logging.xml
              path: logging.xml
---
apiVersion: v1
kind: Service
metadata:
  name: ssoserver-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9443
      nodePort: 31005
    
  selector:
    name: ssoserver-deployment
